### ISSUE TITLE
Passport namespace not being being imported

### ISSUE THREAD

**Issue by nicholas-eden** [danjdewhurst/Laravel-Passport-Facebook-Login#11]
I am getting the following error in 1.5.1:
```
Class 'Danjdewhurst\PassportFacebookLogin\Passport' not found
in FacebookLoginRequestGrant.php (line 28)
```

It looks like the `use ...\Passport` line was removed.

Rolling back to 1.4.1 resolves the issue.

**Comment by Jono20201** [comment]
Hi @nicholas-eden,

Please try v2.0.1 (https://github.com/danjdewhurst/Laravel-Passport-Facebook-Login/releases/tag/2.0.1)

Be aware that you will need to setup the service provider in your `config/app.php` file as Laravel autodiscovery was removed due to a bug.

**Comment by nicholas-eden** [comment]
I had to upgrade to to 5.6, but that seems to have resolved the issue.
