### ISSUE TITLE
Whats the value for client_id and client_secret in request?

### ISSUE THREAD

**Issue by fnocetti** [danjdewhurst/Laravel-Passport-Facebook-Login#15]
Hello,
I didn't get to understand what should be setted as those values while sending the POST request to /oauth/token.

In no part of the docs it says we need to generate a client. Do we?

Just in case, I'm not talking of the fb app id and secret but in the ones required to the user who tries to log in to my application.

Thanks!

**Comment by Jono20201** [comment]
Please review the Laravel Passport docs for this. The client id and client secret are generated using an artisan command.
