### ISSUE TITLE
Proposal: Remove Laravel auto discovery

### ISSUE THREAD

**Issue by Jono20201** [danjdewhurst/Laravel-Passport-Facebook-Login#7]
I'd like to propose removing Laravel's autodiscovery from this package. The reason being is that it relies on Laravel Passport from been booted first, when this does not occur the singleton of `League\OAuth2\Server\AuthorizationServer` that usually gets called, does not. Which creates the error described in the following StackOverflow issue.

https://stackoverflow.com/questions/48608196/target-league-oauth2-server-repositories-clientrepositoryinterface-is-not-inst

**Comment by danjdewhurst** [comment]
Seems like the right thing to do for now, until the auto discovery allows us to specify dependencies.
